Developed a Copy of the New York Times Article Page
MarilenaRoque/NewYorkTimesProject pull request #2
Opened 2020-05-09 00:23 UTC by MarilenaRoque

Added all the elements and style for the Page applicating all the theories learned about the position and floating elements. Including float, grid, box model, flexbox, relative position, different display types, CSS reset.  We also made the recommended validations with Linter and W3 Validator.

#NAVBAR
Position Sticky
Included Icons, Buttons, Logo, and Links
Defined background and border for the Navbar and its elements

#Main
Embedded images and video
Position the section and its elements
Style the text
Included Media Icons
Inflation Section with the Paragraphs overlapping the image

#Asides
Position of the Elements using float and flexbox
Embedded Images 
Included and style the images caption

#BottomNavigation

Positioned all the list with its links
Included the icons
Included the borders

#Footer
Styled and positioned the footer list

2020-05-09 16:45 UTC, rammazzoti2000 commented
### :raised_hands: Pull Request under the review by Alexandru Bangau :raised_hands:

2020-05-09 17:28 UTC, rammazzoti2000 requested changes
#### Hello @MarilenaRoque and @krash46 :raised_hands: , my name is Aleaxndru and I am your code reviewer for this project, by the way awesome work :1st_place_medal: 
You did great work on this project, and have handled very well the use of flexbox and grid model.
- The readme file is descriptive, the pull request has meaningful title and description.
- The commits are short and descriptive.
- Good use of  HTML semantic :muscle: 
There are still a few issues that are preventing me from approving this project, please see the comments bellow
### :stop_sign: Required Changes :construction: :construction_worker_woman: 
- [x] The navbar logo should be a link to the [original page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0) :point_left: 
- [x] The More Popular articles on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) should be links. Wrap them in anchor tags with empty links (`href="#"`)
- [x] In the More in Astronomy and Space it should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)); since the articles you have are different from the actual articles they have on the original page, use anchor tags with empty links (`href="#"`)
#### 
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>

### :stop_sign:  Status: Changes required.

2020-05-09 17:28 UTC, rammazzoti2000 commented on index.html
> +        <img alt="New York Times Logo" src="assets/images/nyt-logo.png" />
the image should be a link, wrap it in an anchor tag

2020-05-09 17:28 UTC, rammazzoti2000 commented on index.html
> +      <aside class="MostPopular">
The More Popular articles on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) should be links.

2020-05-09 17:28 UTC, rammazzoti2000 commented on index.html
> +      <aside class="SpaceAstronomy rows-asside">
In the More in Astronomy and Space it should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

2020-05-09 17:28 UTC, rammazzoti2000 commented on index.html
> +      <aside class="SpaceAstronomy rows-asside">
In the More in Astronomy and Space it should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

2020-05-09 17:28 UTC, rammazzoti2000 commented on index.html
> +      <aside class="EditorPicks rows-asside">
In the More in Astronomy and Space it should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

2020-05-09 17:29 UTC, rammazzoti2000 requested changes
### :stop_sign: Status: Required Changes

2020-05-11 15:50 UTC, MarilenaRoque commented
Thank you for the awesome review!

All the requirements for the approval were fitted. 

- The navbar is a link fo the original page
-The Most Popular Section is a link and also all the articles inside are links to articles on the original page.
-The Images and Subtitles in the More in Astronomy and Space are links for original articles on the original webpage

Additionally, we have added some new features, and style to the page looks more similar to the real one:

- Added functionality for the NavBar Buttons
-Added links for the Create Login Section
-Added links to the original page for the links inside the Text Container
-Set up the hover change color for the Subtitles of the Asides Articles

2020-05-11 21:23 UTC, addod19 approved these changes
## Status: Approved :trophy: :airplane: 

Hi @MarilenaRoque and @krash46, congratulations on fixing all the comments pointed out by the previous TSE :smile: On this note, I hereby approve your project :+1: However before merging to master, I have one optional comment I need you to address.
[OPTIONAL]
Kindly implement the sticky footer as you did for the nav

Good luck with your next project :+1: 
Do not forget to submit the project completion form after merging
_Happy coding_ :woman_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-05-12 14:40 UTC, merged